/*
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cashfree.pg.model;

import java.util.Objects;
import com.cashfree.pg.model.LinkPlanEntity;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.cashfree.pg.JSON;

/**
 * Payment link subscription object for recurring payments.
 */
@Schema(description = "Payment link subscription object for recurring payments.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-19T17:47:33.559854480Z[Etc/UTC]")
public class LinkSubscriptionEntity {
  public static final String SERIALIZED_NAME_PLAN_DETAILS = "plan_details";
  @SerializedName(SERIALIZED_NAME_PLAN_DETAILS)
  private LinkPlanEntity planDetails;

  public static final String SERIALIZED_NAME_AUTHORIZATION_AMOUNT_REFUND = "authorization_amount_refund";
  @SerializedName(SERIALIZED_NAME_AUTHORIZATION_AMOUNT_REFUND)
  private Boolean authorizationAmountRefund;

  public static final String SERIALIZED_NAME_SUBSCRIPTION_EXPIRY_TIME = "subscription_expiry_time";
  @SerializedName(SERIALIZED_NAME_SUBSCRIPTION_EXPIRY_TIME)
  private String subscriptionExpiryTime;

  public static final String SERIALIZED_NAME_SUBSCRIPTION_FIRST_CHARGE_TIME = "subscription_first_charge_time";
  @SerializedName(SERIALIZED_NAME_SUBSCRIPTION_FIRST_CHARGE_TIME)
  private String subscriptionFirstChargeTime;

  public LinkSubscriptionEntity() {
  }

  public LinkSubscriptionEntity planDetails(LinkPlanEntity planDetails) {
    
    this.planDetails = planDetails;
    return this;
  }

   /**
   * Get planDetails
   * @return planDetails
  **/
  @javax.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  public LinkPlanEntity getPlanDetails() {
    return planDetails;
  }


  public void setPlanDetails(LinkPlanEntity planDetails) {
    this.planDetails = planDetails;
  }


  public LinkSubscriptionEntity authorizationAmountRefund(Boolean authorizationAmountRefund) {
    
    this.authorizationAmountRefund = authorizationAmountRefund;
    return this;
  }

   /**
   * Indicates whether the authorization amount should be refunded to the customer automatically. Merchants can use this field to specify if the authorized funds should be returned to the customer after authorization of the subscription.
   * @return authorizationAmountRefund
  **/
  @javax.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Indicates whether the authorization amount should be refunded to the customer automatically. Merchants can use this field to specify if the authorized funds should be returned to the customer after authorization of the subscription.")
  public Boolean getAuthorizationAmountRefund() {
    return authorizationAmountRefund;
  }


  public void setAuthorizationAmountRefund(Boolean authorizationAmountRefund) {
    this.authorizationAmountRefund = authorizationAmountRefund;
  }


  public LinkSubscriptionEntity subscriptionExpiryTime(String subscriptionExpiryTime) {
    
    this.subscriptionExpiryTime = subscriptionExpiryTime;
    return this;
  }

   /**
   * Time at which the subscription will expire.
   * @return subscriptionExpiryTime
  **/
  @javax.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Time at which the subscription will expire.")
  public String getSubscriptionExpiryTime() {
    return subscriptionExpiryTime;
  }


  public void setSubscriptionExpiryTime(String subscriptionExpiryTime) {
    this.subscriptionExpiryTime = subscriptionExpiryTime;
  }


  public LinkSubscriptionEntity subscriptionFirstChargeTime(String subscriptionFirstChargeTime) {
    
    this.subscriptionFirstChargeTime = subscriptionFirstChargeTime;
    return this;
  }

   /**
   * Time at which the first charge for the subscription will be processed.
   * @return subscriptionFirstChargeTime
  **/
  @javax.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Time at which the first charge for the subscription will be processed.")
  public String getSubscriptionFirstChargeTime() {
    return subscriptionFirstChargeTime;
  }


  public void setSubscriptionFirstChargeTime(String subscriptionFirstChargeTime) {
    this.subscriptionFirstChargeTime = subscriptionFirstChargeTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LinkSubscriptionEntity linkSubscriptionEntity = (LinkSubscriptionEntity) o;
    return Objects.equals(this.planDetails, linkSubscriptionEntity.planDetails) &&
        Objects.equals(this.authorizationAmountRefund, linkSubscriptionEntity.authorizationAmountRefund) &&
        Objects.equals(this.subscriptionExpiryTime, linkSubscriptionEntity.subscriptionExpiryTime) &&
        Objects.equals(this.subscriptionFirstChargeTime, linkSubscriptionEntity.subscriptionFirstChargeTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(planDetails, authorizationAmountRefund, subscriptionExpiryTime, subscriptionFirstChargeTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LinkSubscriptionEntity {\n");
    sb.append("    planDetails: ").append(toIndentedString(planDetails)).append("\n");
    sb.append("    authorizationAmountRefund: ").append(toIndentedString(authorizationAmountRefund)).append("\n");
    sb.append("    subscriptionExpiryTime: ").append(toIndentedString(subscriptionExpiryTime)).append("\n");
    sb.append("    subscriptionFirstChargeTime: ").append(toIndentedString(subscriptionFirstChargeTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("plan_details");
    openapiFields.add("authorization_amount_refund");
    openapiFields.add("subscription_expiry_time");
    openapiFields.add("subscription_first_charge_time");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to LinkSubscriptionEntity
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {

        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `plan_details`
      if (jsonObj.get("plan_details") != null && !jsonObj.get("plan_details").isJsonNull()) {
        LinkPlanEntity.validateJsonElement(jsonObj.get("plan_details"));
      }
      if ((jsonObj.get("subscription_expiry_time") != null && !jsonObj.get("subscription_expiry_time").isJsonNull()) && !jsonObj.get("subscription_expiry_time").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `subscription_expiry_time` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subscription_expiry_time").toString()));
      }
      if ((jsonObj.get("subscription_first_charge_time") != null && !jsonObj.get("subscription_first_charge_time").isJsonNull()) && !jsonObj.get("subscription_first_charge_time").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `subscription_first_charge_time` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subscription_first_charge_time").toString()));
      }
  }


  /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to LinkSubscriptionEntity
  */
  public static boolean validateJsonElementForOneOf(JsonElement jsonElement) throws IOException {

        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `plan_details`
      if (jsonObj.get("plan_details") != null && !jsonObj.get("plan_details").isJsonNull()) {
        LinkPlanEntity.validateJsonElement(jsonObj.get("plan_details"));
        return true;
      }
      if ((jsonObj.get("subscription_expiry_time") != null && !jsonObj.get("subscription_expiry_time").isJsonNull()) && !jsonObj.get("subscription_expiry_time").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `subscription_expiry_time` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subscription_expiry_time").toString()));
      }
      if ((jsonObj.get("subscription_first_charge_time") != null && !jsonObj.get("subscription_first_charge_time").isJsonNull()) && !jsonObj.get("subscription_first_charge_time").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `subscription_first_charge_time` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subscription_first_charge_time").toString()));
      }
      return false;
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!LinkSubscriptionEntity.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'LinkSubscriptionEntity' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<LinkSubscriptionEntity> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(LinkSubscriptionEntity.class));

       return (TypeAdapter<T>) new TypeAdapter<LinkSubscriptionEntity>() {
           @Override
           public void write(JsonWriter out, LinkSubscriptionEntity value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public LinkSubscriptionEntity read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of LinkSubscriptionEntity given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of LinkSubscriptionEntity
  * @throws IOException if the JSON string is invalid with respect to LinkSubscriptionEntity
  */
  public static LinkSubscriptionEntity fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LinkSubscriptionEntity.class);
  }

 /**
  * Convert an instance of LinkSubscriptionEntity to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

