/*
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cashfree.pg.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.cashfree.pg.JSON;

/**
 * Filters for this order. Card bins, card schemes, card issuing bank and card suffixes.
 */
@Schema(description = "Filters for this order. Card bins, card schemes, card issuing bank and card suffixes.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-19T17:55:22.134146148Z[Etc/UTC]")
public class OrderPaymentMethodFilters {
  public static final String SERIALIZED_NAME_CARD_EMI_TENURE = "card_emi_tenure";
  @SerializedName(SERIALIZED_NAME_CARD_EMI_TENURE)
  private Integer cardEmiTenure;

  public static final String SERIALIZED_NAME_CARD_EMI_BINS = "card_emi_bins";
  @SerializedName(SERIALIZED_NAME_CARD_EMI_BINS)
  private List<Integer> cardEmiBins = new ArrayList<>();

  public static final String SERIALIZED_NAME_CARD_EMI_SCHEMES = "card_emi_schemes";
  @SerializedName(SERIALIZED_NAME_CARD_EMI_SCHEMES)
  private List<String> cardEmiSchemes = new ArrayList<>();

  public static final String SERIALIZED_NAME_CARD_EMI_SUFFIX = "card_emi_suffix";
  @SerializedName(SERIALIZED_NAME_CARD_EMI_SUFFIX)
  private List<Integer> cardEmiSuffix = new ArrayList<>();

  public static final String SERIALIZED_NAME_CARD_EMI_ISSUING_BANK = "card_emi_issuing_bank";
  @SerializedName(SERIALIZED_NAME_CARD_EMI_ISSUING_BANK)
  private List<String> cardEmiIssuingBank = new ArrayList<>();

  public static final String SERIALIZED_NAME_CARD_BINS = "card_bins";
  @SerializedName(SERIALIZED_NAME_CARD_BINS)
  private List<Integer> cardBins = new ArrayList<>();

  public static final String SERIALIZED_NAME_CARD_SCHEMES = "card_schemes";
  @SerializedName(SERIALIZED_NAME_CARD_SCHEMES)
  private List<String> cardSchemes = new ArrayList<>();

  public static final String SERIALIZED_NAME_CARD_SUFFIX = "card_suffix";
  @SerializedName(SERIALIZED_NAME_CARD_SUFFIX)
  private List<Integer> cardSuffix = new ArrayList<>();

  public static final String SERIALIZED_NAME_CARD_ISSUING_BANK = "card_issuing_bank";
  @SerializedName(SERIALIZED_NAME_CARD_ISSUING_BANK)
  private List<String> cardIssuingBank = new ArrayList<>();

  public OrderPaymentMethodFilters() {
  }

  public OrderPaymentMethodFilters cardEmiTenure(Integer cardEmiTenure) {
    
    this.cardEmiTenure = cardEmiTenure;
    return this;
  }

   /**
   * Allowed card EMI tenure for the order.
   * minimum: 3
   * maximum: 36
   * @return cardEmiTenure
  **/
  @javax.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Allowed card EMI tenure for the order.")
  public Integer getCardEmiTenure() {
    return cardEmiTenure;
  }


  public void setCardEmiTenure(Integer cardEmiTenure) {
    this.cardEmiTenure = cardEmiTenure;
  }


  public OrderPaymentMethodFilters cardEmiBins(List<Integer> cardEmiBins) {
    
    this.cardEmiBins = cardEmiBins;
    return this;
  }

  public OrderPaymentMethodFilters addcardEmiBinsItem(Integer cardEmiBinsItem) {
    if (this.cardEmiBins == null) {
      this.cardEmiBins = new ArrayList<>();
    }
    this.cardEmiBins.add(cardEmiBinsItem);
    return this;
  }

   /**
   * Allowed card EMI bins for the order.
   * @return cardEmiBins
  **/
  @javax.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Allowed card EMI bins for the order.")
  public List<Integer> getCardEmiBins() {
    return cardEmiBins;
  }


  public void setCardEmiBins(List<Integer> cardEmiBins) {
    this.cardEmiBins = cardEmiBins;
  }


  public OrderPaymentMethodFilters cardEmiSchemes(List<String> cardEmiSchemes) {
    
    this.cardEmiSchemes = cardEmiSchemes;
    return this;
  }

  public OrderPaymentMethodFilters addcardEmiSchemesItem(String cardEmiSchemesItem) {
    if (this.cardEmiSchemes == null) {
      this.cardEmiSchemes = new ArrayList<>();
    }
    this.cardEmiSchemes.add(cardEmiSchemesItem);
    return this;
  }

   /**
   * Allowed card EMI schemes for the order.
   * @return cardEmiSchemes
  **/
  @javax.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Allowed card EMI schemes for the order.")
  public List<String> getCardEmiSchemes() {
    return cardEmiSchemes;
  }


  public void setCardEmiSchemes(List<String> cardEmiSchemes) {
    this.cardEmiSchemes = cardEmiSchemes;
  }


  public OrderPaymentMethodFilters cardEmiSuffix(List<Integer> cardEmiSuffix) {
    
    this.cardEmiSuffix = cardEmiSuffix;
    return this;
  }

  public OrderPaymentMethodFilters addcardEmiSuffixItem(Integer cardEmiSuffixItem) {
    if (this.cardEmiSuffix == null) {
      this.cardEmiSuffix = new ArrayList<>();
    }
    this.cardEmiSuffix.add(cardEmiSuffixItem);
    return this;
  }

   /**
   * Allowed card EMI suffixes for the order.
   * @return cardEmiSuffix
  **/
  @javax.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Allowed card EMI suffixes for the order.")
  public List<Integer> getCardEmiSuffix() {
    return cardEmiSuffix;
  }


  public void setCardEmiSuffix(List<Integer> cardEmiSuffix) {
    this.cardEmiSuffix = cardEmiSuffix;
  }


  public OrderPaymentMethodFilters cardEmiIssuingBank(List<String> cardEmiIssuingBank) {
    
    this.cardEmiIssuingBank = cardEmiIssuingBank;
    return this;
  }

  public OrderPaymentMethodFilters addcardEmiIssuingBankItem(String cardEmiIssuingBankItem) {
    if (this.cardEmiIssuingBank == null) {
      this.cardEmiIssuingBank = new ArrayList<>();
    }
    this.cardEmiIssuingBank.add(cardEmiIssuingBankItem);
    return this;
  }

   /**
   * Allowed card EMI issuing bank for the order.
   * @return cardEmiIssuingBank
  **/
  @javax.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Allowed card EMI issuing bank for the order.")
  public List<String> getCardEmiIssuingBank() {
    return cardEmiIssuingBank;
  }


  public void setCardEmiIssuingBank(List<String> cardEmiIssuingBank) {
    this.cardEmiIssuingBank = cardEmiIssuingBank;
  }


  public OrderPaymentMethodFilters cardBins(List<Integer> cardBins) {
    
    this.cardBins = cardBins;
    return this;
  }

  public OrderPaymentMethodFilters addcardBinsItem(Integer cardBinsItem) {
    if (this.cardBins == null) {
      this.cardBins = new ArrayList<>();
    }
    this.cardBins.add(cardBinsItem);
    return this;
  }

   /**
   * Allowed card bins for the order.
   * @return cardBins
  **/
  @javax.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Allowed card bins for the order.")
  public List<Integer> getCardBins() {
    return cardBins;
  }


  public void setCardBins(List<Integer> cardBins) {
    this.cardBins = cardBins;
  }


  public OrderPaymentMethodFilters cardSchemes(List<String> cardSchemes) {
    
    this.cardSchemes = cardSchemes;
    return this;
  }

  public OrderPaymentMethodFilters addcardSchemesItem(String cardSchemesItem) {
    if (this.cardSchemes == null) {
      this.cardSchemes = new ArrayList<>();
    }
    this.cardSchemes.add(cardSchemesItem);
    return this;
  }

   /**
   * Allowed card schemes for the order.
   * @return cardSchemes
  **/
  @javax.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Allowed card schemes for the order.")
  public List<String> getCardSchemes() {
    return cardSchemes;
  }


  public void setCardSchemes(List<String> cardSchemes) {
    this.cardSchemes = cardSchemes;
  }


  public OrderPaymentMethodFilters cardSuffix(List<Integer> cardSuffix) {
    
    this.cardSuffix = cardSuffix;
    return this;
  }

  public OrderPaymentMethodFilters addcardSuffixItem(Integer cardSuffixItem) {
    if (this.cardSuffix == null) {
      this.cardSuffix = new ArrayList<>();
    }
    this.cardSuffix.add(cardSuffixItem);
    return this;
  }

   /**
   * Allowed card suffixes for the order.
   * @return cardSuffix
  **/
  @javax.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Allowed card suffixes for the order.")
  public List<Integer> getCardSuffix() {
    return cardSuffix;
  }


  public void setCardSuffix(List<Integer> cardSuffix) {
    this.cardSuffix = cardSuffix;
  }


  public OrderPaymentMethodFilters cardIssuingBank(List<String> cardIssuingBank) {
    
    this.cardIssuingBank = cardIssuingBank;
    return this;
  }

  public OrderPaymentMethodFilters addcardIssuingBankItem(String cardIssuingBankItem) {
    if (this.cardIssuingBank == null) {
      this.cardIssuingBank = new ArrayList<>();
    }
    this.cardIssuingBank.add(cardIssuingBankItem);
    return this;
  }

   /**
   * Allowed card issuing bank for the order.
   * @return cardIssuingBank
  **/
  @javax.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Allowed card issuing bank for the order.")
  public List<String> getCardIssuingBank() {
    return cardIssuingBank;
  }


  public void setCardIssuingBank(List<String> cardIssuingBank) {
    this.cardIssuingBank = cardIssuingBank;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderPaymentMethodFilters orderPaymentMethodFilters = (OrderPaymentMethodFilters) o;
    return Objects.equals(this.cardEmiTenure, orderPaymentMethodFilters.cardEmiTenure) &&
        Objects.equals(this.cardEmiBins, orderPaymentMethodFilters.cardEmiBins) &&
        Objects.equals(this.cardEmiSchemes, orderPaymentMethodFilters.cardEmiSchemes) &&
        Objects.equals(this.cardEmiSuffix, orderPaymentMethodFilters.cardEmiSuffix) &&
        Objects.equals(this.cardEmiIssuingBank, orderPaymentMethodFilters.cardEmiIssuingBank) &&
        Objects.equals(this.cardBins, orderPaymentMethodFilters.cardBins) &&
        Objects.equals(this.cardSchemes, orderPaymentMethodFilters.cardSchemes) &&
        Objects.equals(this.cardSuffix, orderPaymentMethodFilters.cardSuffix) &&
        Objects.equals(this.cardIssuingBank, orderPaymentMethodFilters.cardIssuingBank);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cardEmiTenure, cardEmiBins, cardEmiSchemes, cardEmiSuffix, cardEmiIssuingBank, cardBins, cardSchemes, cardSuffix, cardIssuingBank);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderPaymentMethodFilters {\n");
    sb.append("    cardEmiTenure: ").append(toIndentedString(cardEmiTenure)).append("\n");
    sb.append("    cardEmiBins: ").append(toIndentedString(cardEmiBins)).append("\n");
    sb.append("    cardEmiSchemes: ").append(toIndentedString(cardEmiSchemes)).append("\n");
    sb.append("    cardEmiSuffix: ").append(toIndentedString(cardEmiSuffix)).append("\n");
    sb.append("    cardEmiIssuingBank: ").append(toIndentedString(cardEmiIssuingBank)).append("\n");
    sb.append("    cardBins: ").append(toIndentedString(cardBins)).append("\n");
    sb.append("    cardSchemes: ").append(toIndentedString(cardSchemes)).append("\n");
    sb.append("    cardSuffix: ").append(toIndentedString(cardSuffix)).append("\n");
    sb.append("    cardIssuingBank: ").append(toIndentedString(cardIssuingBank)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("card_emi_tenure");
    openapiFields.add("card_emi_bins");
    openapiFields.add("card_emi_schemes");
    openapiFields.add("card_emi_suffix");
    openapiFields.add("card_emi_issuing_bank");
    openapiFields.add("card_bins");
    openapiFields.add("card_schemes");
    openapiFields.add("card_suffix");
    openapiFields.add("card_issuing_bank");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to OrderPaymentMethodFilters
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {

        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("card_emi_bins") != null && !jsonObj.get("card_emi_bins").isJsonNull() && !jsonObj.get("card_emi_bins").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `card_emi_bins` to be an array in the JSON string but got `%s`", jsonObj.get("card_emi_bins").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("card_emi_schemes") != null && !jsonObj.get("card_emi_schemes").isJsonNull() && !jsonObj.get("card_emi_schemes").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `card_emi_schemes` to be an array in the JSON string but got `%s`", jsonObj.get("card_emi_schemes").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("card_emi_suffix") != null && !jsonObj.get("card_emi_suffix").isJsonNull() && !jsonObj.get("card_emi_suffix").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `card_emi_suffix` to be an array in the JSON string but got `%s`", jsonObj.get("card_emi_suffix").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("card_emi_issuing_bank") != null && !jsonObj.get("card_emi_issuing_bank").isJsonNull() && !jsonObj.get("card_emi_issuing_bank").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `card_emi_issuing_bank` to be an array in the JSON string but got `%s`", jsonObj.get("card_emi_issuing_bank").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("card_bins") != null && !jsonObj.get("card_bins").isJsonNull() && !jsonObj.get("card_bins").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `card_bins` to be an array in the JSON string but got `%s`", jsonObj.get("card_bins").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("card_schemes") != null && !jsonObj.get("card_schemes").isJsonNull() && !jsonObj.get("card_schemes").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `card_schemes` to be an array in the JSON string but got `%s`", jsonObj.get("card_schemes").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("card_suffix") != null && !jsonObj.get("card_suffix").isJsonNull() && !jsonObj.get("card_suffix").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `card_suffix` to be an array in the JSON string but got `%s`", jsonObj.get("card_suffix").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("card_issuing_bank") != null && !jsonObj.get("card_issuing_bank").isJsonNull() && !jsonObj.get("card_issuing_bank").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `card_issuing_bank` to be an array in the JSON string but got `%s`", jsonObj.get("card_issuing_bank").toString()));
      }
  }


  /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to OrderPaymentMethodFilters
  */
  public static boolean validateJsonElementForOneOf(JsonElement jsonElement) throws IOException {

        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("card_emi_bins") != null && !jsonObj.get("card_emi_bins").isJsonNull() && !jsonObj.get("card_emi_bins").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `card_emi_bins` to be an array in the JSON string but got `%s`", jsonObj.get("card_emi_bins").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("card_emi_schemes") != null && !jsonObj.get("card_emi_schemes").isJsonNull() && !jsonObj.get("card_emi_schemes").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `card_emi_schemes` to be an array in the JSON string but got `%s`", jsonObj.get("card_emi_schemes").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("card_emi_suffix") != null && !jsonObj.get("card_emi_suffix").isJsonNull() && !jsonObj.get("card_emi_suffix").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `card_emi_suffix` to be an array in the JSON string but got `%s`", jsonObj.get("card_emi_suffix").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("card_emi_issuing_bank") != null && !jsonObj.get("card_emi_issuing_bank").isJsonNull() && !jsonObj.get("card_emi_issuing_bank").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `card_emi_issuing_bank` to be an array in the JSON string but got `%s`", jsonObj.get("card_emi_issuing_bank").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("card_bins") != null && !jsonObj.get("card_bins").isJsonNull() && !jsonObj.get("card_bins").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `card_bins` to be an array in the JSON string but got `%s`", jsonObj.get("card_bins").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("card_schemes") != null && !jsonObj.get("card_schemes").isJsonNull() && !jsonObj.get("card_schemes").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `card_schemes` to be an array in the JSON string but got `%s`", jsonObj.get("card_schemes").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("card_suffix") != null && !jsonObj.get("card_suffix").isJsonNull() && !jsonObj.get("card_suffix").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `card_suffix` to be an array in the JSON string but got `%s`", jsonObj.get("card_suffix").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("card_issuing_bank") != null && !jsonObj.get("card_issuing_bank").isJsonNull() && !jsonObj.get("card_issuing_bank").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `card_issuing_bank` to be an array in the JSON string but got `%s`", jsonObj.get("card_issuing_bank").toString()));
      }
      return false;
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OrderPaymentMethodFilters.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OrderPaymentMethodFilters' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OrderPaymentMethodFilters> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OrderPaymentMethodFilters.class));

       return (TypeAdapter<T>) new TypeAdapter<OrderPaymentMethodFilters>() {
           @Override
           public void write(JsonWriter out, OrderPaymentMethodFilters value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OrderPaymentMethodFilters read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of OrderPaymentMethodFilters given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of OrderPaymentMethodFilters
  * @throws IOException if the JSON string is invalid with respect to OrderPaymentMethodFilters
  */
  public static OrderPaymentMethodFilters fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OrderPaymentMethodFilters.class);
  }

 /**
  * Convert an instance of OrderPaymentMethodFilters to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

