/*
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cashfree.pg.model;

import java.util.Objects;
import com.cashfree.pg.model.OrderMetaOfferFilters;
import com.cashfree.pg.model.OrderMetaPaymentMethodsFilters;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.cashfree.pg.JSON;

/**
 * Optional meta details to control how the customer pays and how payment journey completes.
 */
@Schema(description = "Optional meta details to control how the customer pays and how payment journey completes.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-19T17:55:22.134146148Z[Etc/UTC]")
public class OrderMeta {
  public static final String SERIALIZED_NAME_RETURN_URL = "return_url";
  @SerializedName(SERIALIZED_NAME_RETURN_URL)
  private String returnUrl;

  public static final String SERIALIZED_NAME_NOTIFY_URL = "notify_url";
  @SerializedName(SERIALIZED_NAME_NOTIFY_URL)
  private String notifyUrl;

  public static final String SERIALIZED_NAME_PAYMENT_METHODS = "payment_methods";
  @SerializedName(SERIALIZED_NAME_PAYMENT_METHODS)
  private Object paymentMethods = null;

  public static final String SERIALIZED_NAME_PAYMENT_METHODS_FILTERS = "payment_methods_filters";
  @SerializedName(SERIALIZED_NAME_PAYMENT_METHODS_FILTERS)
  private OrderMetaPaymentMethodsFilters paymentMethodsFilters;

  public static final String SERIALIZED_NAME_OFFER_FILTERS = "offer_filters";
  @SerializedName(SERIALIZED_NAME_OFFER_FILTERS)
  private OrderMetaOfferFilters offerFilters;

  public static final String SERIALIZED_NAME_UPI_APP_PRIORITY = "upi_app_priority";
  @SerializedName(SERIALIZED_NAME_UPI_APP_PRIORITY)
  private Object upiAppPriority = null;

  public OrderMeta() {
  }

  public OrderMeta returnUrl(String returnUrl) {
    
    this.returnUrl = returnUrl;
    return this;
  }

   /**
   * This is the [URL](https://www.cashfree.com/devstudio/thankyou?order_id&#x3D;devstudio_734905336776434862) to which the customer will be redirected after the payment reaches a terminal state (success, failed or cancelled). We recommend keeping context of &#x60;order_id&#x60; in your &#x60;return_url&#x60; so that you can identify the order when customer lands on your page. Cashfree triggers a **GET request** to this URL. Maximum URL length: 250 characters.
   * @return returnUrl
  **/
  @javax.annotation.Nullable
  @Schema(example = "https://www.cashfree.com/devstudio/thankyou?order_id=devstudio_734905336776434862", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "This is the [URL](https://www.cashfree.com/devstudio/thankyou?order_id=devstudio_734905336776434862) to which the customer will be redirected after the payment reaches a terminal state (success, failed or cancelled). We recommend keeping context of `order_id` in your `return_url` so that you can identify the order when customer lands on your page. Cashfree triggers a **GET request** to this URL. Maximum URL length: 250 characters.")
  public String getReturnUrl() {
    return returnUrl;
  }


  public void setReturnUrl(String returnUrl) {
    this.returnUrl = returnUrl;
  }


  public OrderMeta notifyUrl(String notifyUrl) {
    
    this.notifyUrl = notifyUrl;
    return this;
  }

   /**
   * Notification URL for server-server communication. Useful when user&#39;s connection drops while re-directing. NotifyUrl should be an https URL. Maximum length: 250.
   * @return notifyUrl
  **/
  @javax.annotation.Nullable
  @Schema(example = "https://example.com/cf_notify", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Notification URL for server-server communication. Useful when user's connection drops while re-directing. NotifyUrl should be an https URL. Maximum length: 250.")
  public String getNotifyUrl() {
    return notifyUrl;
  }


  public void setNotifyUrl(String notifyUrl) {
    this.notifyUrl = notifyUrl;
  }


  public OrderMeta paymentMethods(Object paymentMethods) {
    
    this.paymentMethods = paymentMethods;
    return this;
  }

   /**
   * Specifies the allowed payment modes for this order. To restrict payment options,  provide a comma-separated list of values from the following options: &#x60;cc&#x60;, &#x60;dc&#x60;, &#x60;ccc&#x60;,  &#x60;ppc&#x60;, &#x60;nb&#x60;, &#x60;upi&#x60;, &#x60;paypal&#x60;, &#x60;app&#x60;, &#x60;paylater&#x60;, &#x60;cardlessemi&#x60;, &#x60;dcemi&#x60;, &#x60;ccemi&#x60;,  &#x60;banktransfer&#x60;, &#x60;applepay&#x60;. Leave this field blank to display all available payment methods.
   * @return paymentMethods
  **/
  @javax.annotation.Nullable
  @Schema(example = "cc,dc,upi", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Specifies the allowed payment modes for this order. To restrict payment options,  provide a comma-separated list of values from the following options: `cc`, `dc`, `ccc`,  `ppc`, `nb`, `upi`, `paypal`, `app`, `paylater`, `cardlessemi`, `dcemi`, `ccemi`,  `banktransfer`, `applepay`. Leave this field blank to display all available payment methods.")
  public Object getPaymentMethods() {
    return paymentMethods;
  }


  public void setPaymentMethods(Object paymentMethods) {
    this.paymentMethods = paymentMethods;
  }


  public OrderMeta paymentMethodsFilters(OrderMetaPaymentMethodsFilters paymentMethodsFilters) {
    
    this.paymentMethodsFilters = paymentMethodsFilters;
    return this;
  }

   /**
   * Get paymentMethodsFilters
   * @return paymentMethodsFilters
  **/
  @javax.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  public OrderMetaPaymentMethodsFilters getPaymentMethodsFilters() {
    return paymentMethodsFilters;
  }


  public void setPaymentMethodsFilters(OrderMetaPaymentMethodsFilters paymentMethodsFilters) {
    this.paymentMethodsFilters = paymentMethodsFilters;
  }


  public OrderMeta offerFilters(OrderMetaOfferFilters offerFilters) {
    
    this.offerFilters = offerFilters;
    return this;
  }

   /**
   * Get offerFilters
   * @return offerFilters
  **/
  @javax.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  public OrderMetaOfferFilters getOfferFilters() {
    return offerFilters;
  }


  public void setOfferFilters(OrderMetaOfferFilters offerFilters) {
    this.offerFilters = offerFilters;
  }


  public OrderMeta upiAppPriority(Object upiAppPriority) {
    
    this.upiAppPriority = upiAppPriority;
    return this;
  }

   /**
   * Set the priority of UPI apps that you want to show for this order. Pass values in list among following options - \&quot;gpay\&quot;,\&quot;phonepe\&quot;,\&quot;paytm\&quot;,\&quot;navi\&quot;,\&quot;cred\&quot;,\&quot;supermoney\&quot;,\&quot;amazonpay\&quot;,\&quot;bhim\&quot;,\&quot;mobikwik\&quot;,\&quot;airtel\&quot;,\&quot;popclub\&quot;,\&quot;kiwi\&quot;.
   * @return upiAppPriority
  **/
  @javax.annotation.Nullable
  @Schema(example = "[\"navi\",\"gpay\",\"phonepe\",\"cred\"]", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Set the priority of UPI apps that you want to show for this order. Pass values in list among following options - \"gpay\",\"phonepe\",\"paytm\",\"navi\",\"cred\",\"supermoney\",\"amazonpay\",\"bhim\",\"mobikwik\",\"airtel\",\"popclub\",\"kiwi\".")
  public Object getUpiAppPriority() {
    return upiAppPriority;
  }


  public void setUpiAppPriority(Object upiAppPriority) {
    this.upiAppPriority = upiAppPriority;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderMeta orderMeta = (OrderMeta) o;
    return Objects.equals(this.returnUrl, orderMeta.returnUrl) &&
        Objects.equals(this.notifyUrl, orderMeta.notifyUrl) &&
        Objects.equals(this.paymentMethods, orderMeta.paymentMethods) &&
        Objects.equals(this.paymentMethodsFilters, orderMeta.paymentMethodsFilters) &&
        Objects.equals(this.offerFilters, orderMeta.offerFilters) &&
        Objects.equals(this.upiAppPriority, orderMeta.upiAppPriority);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(returnUrl, notifyUrl, paymentMethods, paymentMethodsFilters, offerFilters, upiAppPriority);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderMeta {\n");
    sb.append("    returnUrl: ").append(toIndentedString(returnUrl)).append("\n");
    sb.append("    notifyUrl: ").append(toIndentedString(notifyUrl)).append("\n");
    sb.append("    paymentMethods: ").append(toIndentedString(paymentMethods)).append("\n");
    sb.append("    paymentMethodsFilters: ").append(toIndentedString(paymentMethodsFilters)).append("\n");
    sb.append("    offerFilters: ").append(toIndentedString(offerFilters)).append("\n");
    sb.append("    upiAppPriority: ").append(toIndentedString(upiAppPriority)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("return_url");
    openapiFields.add("notify_url");
    openapiFields.add("payment_methods");
    openapiFields.add("payment_methods_filters");
    openapiFields.add("offer_filters");
    openapiFields.add("upi_app_priority");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to OrderMeta
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {

        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("return_url") != null && !jsonObj.get("return_url").isJsonNull()) && !jsonObj.get("return_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `return_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("return_url").toString()));
      }
      if ((jsonObj.get("notify_url") != null && !jsonObj.get("notify_url").isJsonNull()) && !jsonObj.get("notify_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `notify_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("notify_url").toString()));
      }
      // validate the optional field `payment_methods_filters`
      if (jsonObj.get("payment_methods_filters") != null && !jsonObj.get("payment_methods_filters").isJsonNull()) {
        OrderMetaPaymentMethodsFilters.validateJsonElement(jsonObj.get("payment_methods_filters"));
      }
      // validate the optional field `offer_filters`
      if (jsonObj.get("offer_filters") != null && !jsonObj.get("offer_filters").isJsonNull()) {
        OrderMetaOfferFilters.validateJsonElement(jsonObj.get("offer_filters"));
      }
  }


  /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to OrderMeta
  */
  public static boolean validateJsonElementForOneOf(JsonElement jsonElement) throws IOException {

        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("return_url") != null && !jsonObj.get("return_url").isJsonNull()) && !jsonObj.get("return_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `return_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("return_url").toString()));
      }
      if ((jsonObj.get("notify_url") != null && !jsonObj.get("notify_url").isJsonNull()) && !jsonObj.get("notify_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `notify_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("notify_url").toString()));
      }
      // validate the optional field `payment_methods_filters`
      if (jsonObj.get("payment_methods_filters") != null && !jsonObj.get("payment_methods_filters").isJsonNull()) {
        OrderMetaPaymentMethodsFilters.validateJsonElement(jsonObj.get("payment_methods_filters"));
        return true;
      }
      // validate the optional field `offer_filters`
      if (jsonObj.get("offer_filters") != null && !jsonObj.get("offer_filters").isJsonNull()) {
        OrderMetaOfferFilters.validateJsonElement(jsonObj.get("offer_filters"));
        return true;
      }
      return false;
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OrderMeta.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OrderMeta' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OrderMeta> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OrderMeta.class));

       return (TypeAdapter<T>) new TypeAdapter<OrderMeta>() {
           @Override
           public void write(JsonWriter out, OrderMeta value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OrderMeta read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of OrderMeta given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of OrderMeta
  * @throws IOException if the JSON string is invalid with respect to OrderMeta
  */
  public static OrderMeta fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OrderMeta.class);
  }

 /**
  * Convert an instance of OrderMeta to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

