/*
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cashfree.pg.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.cashfree.pg.JSON;

/**
 * Object to simulate a settlement request.
 */
@Schema(description = "Object to simulate a settlement request.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-19T17:55:22.134146148Z[Etc/UTC]")
public class SettlementSimulationResponse {
  public static final String SERIALIZED_NAME_SIMULATION_ID = "simulation_id";
  @SerializedName(SERIALIZED_NAME_SIMULATION_ID)
  private String simulationId;

  public static final String SERIALIZED_NAME_ENTITY = "entity";
  @SerializedName(SERIALIZED_NAME_ENTITY)
  private String entity;

  public static final String SERIALIZED_NAME_SETTLEMENT_IDS = "settlement_ids";
  @SerializedName(SERIALIZED_NAME_SETTLEMENT_IDS)
  private List<BigDecimal> settlementIds = new ArrayList<>();

  public static final String SERIALIZED_NAME_SIMULATION_STATUS = "simulation_status";
  @SerializedName(SERIALIZED_NAME_SIMULATION_STATUS)
  private String simulationStatus;

  public SettlementSimulationResponse() {
  }

  public SettlementSimulationResponse simulationId(String simulationId) {
    
    this.simulationId = simulationId;
    return this;
  }

   /**
   * A unique identifier for the simulation request.
   * @return simulationId
  **/
  @javax.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "A unique identifier for the simulation request.")
  public String getSimulationId() {
    return simulationId;
  }


  public void setSimulationId(String simulationId) {
    this.simulationId = simulationId;
  }


  public SettlementSimulationResponse entity(String entity) {
    
    this.entity = entity;
    return this;
  }

   /**
   * Entity type for which the simulation is performed. Example: \&quot;SETTLEMENTS\&quot;.
   * @return entity
  **/
  @javax.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Entity type for which the simulation is performed. Example: \"SETTLEMENTS\".")
  public String getEntity() {
    return entity;
  }


  public void setEntity(String entity) {
    this.entity = entity;
  }


  public SettlementSimulationResponse settlementIds(List<BigDecimal> settlementIds) {
    
    this.settlementIds = settlementIds;
    return this;
  }

  public SettlementSimulationResponse addsettlementIdsItem(BigDecimal settlementIdsItem) {
    if (this.settlementIds == null) {
      this.settlementIds = new ArrayList<>();
    }
    this.settlementIds.add(settlementIdsItem);
    return this;
  }

   /**
   * List of simulated settlement IDs.
   * @return settlementIds
  **/
  @javax.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "List of simulated settlement IDs.")
  public List<BigDecimal> getSettlementIds() {
    return settlementIds;
  }


  public void setSettlementIds(List<BigDecimal> settlementIds) {
    this.settlementIds = settlementIds;
  }


  public SettlementSimulationResponse simulationStatus(String simulationStatus) {
    
    this.simulationStatus = simulationStatus;
    return this;
  }

   /**
   * Status of the simulation request. Example: \&quot;SUCCESS/FAILED/PENDING\&quot;.
   * @return simulationStatus
  **/
  @javax.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Status of the simulation request. Example: \"SUCCESS/FAILED/PENDING\".")
  public String getSimulationStatus() {
    return simulationStatus;
  }


  public void setSimulationStatus(String simulationStatus) {
    this.simulationStatus = simulationStatus;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SettlementSimulationResponse settlementSimulationResponse = (SettlementSimulationResponse) o;
    return Objects.equals(this.simulationId, settlementSimulationResponse.simulationId) &&
        Objects.equals(this.entity, settlementSimulationResponse.entity) &&
        Objects.equals(this.settlementIds, settlementSimulationResponse.settlementIds) &&
        Objects.equals(this.simulationStatus, settlementSimulationResponse.simulationStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(simulationId, entity, settlementIds, simulationStatus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SettlementSimulationResponse {\n");
    sb.append("    simulationId: ").append(toIndentedString(simulationId)).append("\n");
    sb.append("    entity: ").append(toIndentedString(entity)).append("\n");
    sb.append("    settlementIds: ").append(toIndentedString(settlementIds)).append("\n");
    sb.append("    simulationStatus: ").append(toIndentedString(simulationStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("simulation_id");
    openapiFields.add("entity");
    openapiFields.add("settlement_ids");
    openapiFields.add("simulation_status");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to SettlementSimulationResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {

        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("simulation_id") != null && !jsonObj.get("simulation_id").isJsonNull()) && !jsonObj.get("simulation_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `simulation_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("simulation_id").toString()));
      }
      if ((jsonObj.get("entity") != null && !jsonObj.get("entity").isJsonNull()) && !jsonObj.get("entity").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `entity` to be a primitive type in the JSON string but got `%s`", jsonObj.get("entity").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("settlement_ids") != null && !jsonObj.get("settlement_ids").isJsonNull() && !jsonObj.get("settlement_ids").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `settlement_ids` to be an array in the JSON string but got `%s`", jsonObj.get("settlement_ids").toString()));
      }
      if ((jsonObj.get("simulation_status") != null && !jsonObj.get("simulation_status").isJsonNull()) && !jsonObj.get("simulation_status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `simulation_status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("simulation_status").toString()));
      }
  }


  /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to SettlementSimulationResponse
  */
  public static boolean validateJsonElementForOneOf(JsonElement jsonElement) throws IOException {

        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("simulation_id") != null && !jsonObj.get("simulation_id").isJsonNull()) && !jsonObj.get("simulation_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `simulation_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("simulation_id").toString()));
      }
      if ((jsonObj.get("entity") != null && !jsonObj.get("entity").isJsonNull()) && !jsonObj.get("entity").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `entity` to be a primitive type in the JSON string but got `%s`", jsonObj.get("entity").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("settlement_ids") != null && !jsonObj.get("settlement_ids").isJsonNull() && !jsonObj.get("settlement_ids").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `settlement_ids` to be an array in the JSON string but got `%s`", jsonObj.get("settlement_ids").toString()));
      }
      if ((jsonObj.get("simulation_status") != null && !jsonObj.get("simulation_status").isJsonNull()) && !jsonObj.get("simulation_status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `simulation_status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("simulation_status").toString()));
      }
      return false;
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SettlementSimulationResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SettlementSimulationResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SettlementSimulationResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SettlementSimulationResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<SettlementSimulationResponse>() {
           @Override
           public void write(JsonWriter out, SettlementSimulationResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SettlementSimulationResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SettlementSimulationResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SettlementSimulationResponse
  * @throws IOException if the JSON string is invalid with respect to SettlementSimulationResponse
  */
  public static SettlementSimulationResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SettlementSimulationResponse.class);
  }

 /**
  * Convert an instance of SettlementSimulationResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

