/*
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2025-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cashfree.pg.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.cashfree.pg.JSON;

/**
 * StaticSplitRequestSchemeInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-01-23T14:04:19.914397Z[Etc/UTC]")
public class StaticSplitRequestSchemeInner {
  public static final String SERIALIZED_NAME_MERCHANT_VENDOR_ID = "merchantVendorId";
  @SerializedName(SERIALIZED_NAME_MERCHANT_VENDOR_ID)
  private String merchantVendorId;

  public static final String SERIALIZED_NAME_PERCENTAGE = "percentage";
  @SerializedName(SERIALIZED_NAME_PERCENTAGE)
  private String percentage;

  public StaticSplitRequestSchemeInner() {
  }

  public StaticSplitRequestSchemeInner merchantVendorId(String merchantVendorId) {
    
    this.merchantVendorId = merchantVendorId;
    return this;
  }

   /**
   * Specify the merchant vendor ID to create the split scheme for the payment.
   * @return merchantVendorId
  **/
  @javax.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Specify the merchant vendor ID to create the split scheme for the payment.")
  public String getMerchantVendorId() {
    return merchantVendorId;
  }


  public void setMerchantVendorId(String merchantVendorId) {
    this.merchantVendorId = merchantVendorId;
  }


  public StaticSplitRequestSchemeInner percentage(String percentage) {
    
    this.percentage = percentage;
    return this;
  }

   /**
   * Specify the percentage of amount to be split.
   * @return percentage
  **/
  @javax.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Specify the percentage of amount to be split.")
  public String getPercentage() {
    return percentage;
  }


  public void setPercentage(String percentage) {
    this.percentage = percentage;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StaticSplitRequestSchemeInner staticSplitRequestSchemeInner = (StaticSplitRequestSchemeInner) o;
    return Objects.equals(this.merchantVendorId, staticSplitRequestSchemeInner.merchantVendorId) &&
        Objects.equals(this.percentage, staticSplitRequestSchemeInner.percentage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(merchantVendorId, percentage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StaticSplitRequestSchemeInner {\n");
    sb.append("    merchantVendorId: ").append(toIndentedString(merchantVendorId)).append("\n");
    sb.append("    percentage: ").append(toIndentedString(percentage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("merchantVendorId");
    openapiFields.add("percentage");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to StaticSplitRequestSchemeInner
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {

        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("merchantVendorId") != null && !jsonObj.get("merchantVendorId").isJsonNull()) && !jsonObj.get("merchantVendorId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `merchantVendorId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("merchantVendorId").toString()));
      }
      if ((jsonObj.get("percentage") != null && !jsonObj.get("percentage").isJsonNull()) && !jsonObj.get("percentage").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `percentage` to be a primitive type in the JSON string but got `%s`", jsonObj.get("percentage").toString()));
      }
  }


  /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to StaticSplitRequestSchemeInner
  */
  public static boolean validateJsonElementForOneOf(JsonElement jsonElement) throws IOException {

        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("merchantVendorId") != null && !jsonObj.get("merchantVendorId").isJsonNull()) && !jsonObj.get("merchantVendorId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `merchantVendorId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("merchantVendorId").toString()));
      }
      if ((jsonObj.get("percentage") != null && !jsonObj.get("percentage").isJsonNull()) && !jsonObj.get("percentage").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `percentage` to be a primitive type in the JSON string but got `%s`", jsonObj.get("percentage").toString()));
      }
      return false;
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!StaticSplitRequestSchemeInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'StaticSplitRequestSchemeInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<StaticSplitRequestSchemeInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(StaticSplitRequestSchemeInner.class));

       return (TypeAdapter<T>) new TypeAdapter<StaticSplitRequestSchemeInner>() {
           @Override
           public void write(JsonWriter out, StaticSplitRequestSchemeInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public StaticSplitRequestSchemeInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of StaticSplitRequestSchemeInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of StaticSplitRequestSchemeInner
  * @throws IOException if the JSON string is invalid with respect to StaticSplitRequestSchemeInner
  */
  public static StaticSplitRequestSchemeInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, StaticSplitRequestSchemeInner.class);
  }

 /**
  * Convert an instance of StaticSplitRequestSchemeInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

