/*
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2022-09-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cashfree.model;

import com.cashfree.model.Netbanking;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for NetBankingPaymentMethod
 */
public class NetBankingPaymentMethodTest {
    private final NetBankingPaymentMethod model = new NetBankingPaymentMethod();

    /**
     * Model tests for NetBankingPaymentMethod
     */
    @Test
    public void testNetBankingPaymentMethod() {
        // TODO: test NetBankingPaymentMethod
    }

    /**
     * Test the property 'netbanking'
     */
    @Test
    public void netbankingTest() {
        // TODO: test netbanking
    }

}
