/*
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2022-09-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cashfree.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OfferMeta
 */
public class OfferMetaTest {
    private final OfferMeta model = new OfferMeta();

    /**
     * Model tests for OfferMeta
     */
    @Test
    public void testOfferMeta() {
        // TODO: test OfferMeta
    }

    /**
     * Test the property 'offerTitle'
     */
    @Test
    public void offerTitleTest() {
        // TODO: test offerTitle
    }

    /**
     * Test the property 'offerDescription'
     */
    @Test
    public void offerDescriptionTest() {
        // TODO: test offerDescription
    }

    /**
     * Test the property 'offerCode'
     */
    @Test
    public void offerCodeTest() {
        // TODO: test offerCode
    }

    /**
     * Test the property 'offerStartTime'
     */
    @Test
    public void offerStartTimeTest() {
        // TODO: test offerStartTime
    }

    /**
     * Test the property 'offerEndTime'
     */
    @Test
    public void offerEndTimeTest() {
        // TODO: test offerEndTime
    }

}
