/*
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2022-09-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cashfree.model;

import com.cashfree.model.AuthorizationInPaymentsEntity;
import com.cashfree.model.ErrorDetailsInPaymentsEntity;
import com.cashfree.model.PaymentMethodInPaymentsEntity;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaymentEntity
 */
public class PaymentEntityTest {
    private final PaymentEntity model = new PaymentEntity();

    /**
     * Model tests for PaymentEntity
     */
    @Test
    public void testPaymentEntity() {
        // TODO: test PaymentEntity
    }

    /**
     * Test the property 'cfPaymentId'
     */
    @Test
    public void cfPaymentIdTest() {
        // TODO: test cfPaymentId
    }

    /**
     * Test the property 'orderId'
     */
    @Test
    public void orderIdTest() {
        // TODO: test orderId
    }

    /**
     * Test the property 'entity'
     */
    @Test
    public void entityTest() {
        // TODO: test entity
    }

    /**
     * Test the property 'errorDetails'
     */
    @Test
    public void errorDetailsTest() {
        // TODO: test errorDetails
    }

    /**
     * Test the property 'isCaptured'
     */
    @Test
    public void isCapturedTest() {
        // TODO: test isCaptured
    }

    /**
     * Test the property 'orderAmount'
     */
    @Test
    public void orderAmountTest() {
        // TODO: test orderAmount
    }

    /**
     * Test the property 'paymentGroup'
     */
    @Test
    public void paymentGroupTest() {
        // TODO: test paymentGroup
    }

    /**
     * Test the property 'paymentCurrency'
     */
    @Test
    public void paymentCurrencyTest() {
        // TODO: test paymentCurrency
    }

    /**
     * Test the property 'paymentAmount'
     */
    @Test
    public void paymentAmountTest() {
        // TODO: test paymentAmount
    }

    /**
     * Test the property 'paymentTime'
     */
    @Test
    public void paymentTimeTest() {
        // TODO: test paymentTime
    }

    /**
     * Test the property 'paymentCompletionTime'
     */
    @Test
    public void paymentCompletionTimeTest() {
        // TODO: test paymentCompletionTime
    }

    /**
     * Test the property 'paymentStatus'
     */
    @Test
    public void paymentStatusTest() {
        // TODO: test paymentStatus
    }

    /**
     * Test the property 'paymentMessage'
     */
    @Test
    public void paymentMessageTest() {
        // TODO: test paymentMessage
    }

    /**
     * Test the property 'bankReference'
     */
    @Test
    public void bankReferenceTest() {
        // TODO: test bankReference
    }

    /**
     * Test the property 'authId'
     */
    @Test
    public void authIdTest() {
        // TODO: test authId
    }

    /**
     * Test the property 'authorization'
     */
    @Test
    public void authorizationTest() {
        // TODO: test authorization
    }

    /**
     * Test the property 'paymentMethod'
     */
    @Test
    public void paymentMethodTest() {
        // TODO: test paymentMethod
    }

}
