/*
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2022-09-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cashfree.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaymentMethodCardInPaymentsEntity
 */
public class PaymentMethodCardInPaymentsEntityTest {
    private final PaymentMethodCardInPaymentsEntity model = new PaymentMethodCardInPaymentsEntity();

    /**
     * Model tests for PaymentMethodCardInPaymentsEntity
     */
    @Test
    public void testPaymentMethodCardInPaymentsEntity() {
        // TODO: test PaymentMethodCardInPaymentsEntity
    }

    /**
     * Test the property 'channel'
     */
    @Test
    public void channelTest() {
        // TODO: test channel
    }

    /**
     * Test the property 'cardNumber'
     */
    @Test
    public void cardNumberTest() {
        // TODO: test cardNumber
    }

    /**
     * Test the property 'cardNetwork'
     */
    @Test
    public void cardNetworkTest() {
        // TODO: test cardNetwork
    }

    /**
     * Test the property 'cardType'
     */
    @Test
    public void cardTypeTest() {
        // TODO: test cardType
    }

    /**
     * Test the property 'cardCountry'
     */
    @Test
    public void cardCountryTest() {
        // TODO: test cardCountry
    }

    /**
     * Test the property 'cardBankName'
     */
    @Test
    public void cardBankNameTest() {
        // TODO: test cardBankName
    }

    /**
     * Test the property 'cardNetworkReferenceId'
     */
    @Test
    public void cardNetworkReferenceIdTest() {
        // TODO: test cardNetworkReferenceId
    }

}
