/*
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2022-09-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cashfree.model;

import com.cashfree.model.PayOrderRequestPaymentMethod;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PayOrderRequest
 */
public class PayOrderRequestTest {
    private final PayOrderRequest model = new PayOrderRequest();

    /**
     * Model tests for PayOrderRequest
     */
    @Test
    public void testPayOrderRequest() {
        // TODO: test PayOrderRequest
    }

    /**
     * Test the property 'paymentSessionId'
     */
    @Test
    public void paymentSessionIdTest() {
        // TODO: test paymentSessionId
    }

    /**
     * Test the property 'paymentMethod'
     */
    @Test
    public void paymentMethodTest() {
        // TODO: test paymentMethod
    }

    /**
     * Test the property 'saveInstrument'
     */
    @Test
    public void saveInstrumentTest() {
        // TODO: test saveInstrument
    }

    /**
     * Test the property 'offerId'
     */
    @Test
    public void offerIdTest() {
        // TODO: test offerId
    }

}
