/*
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2022-09-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cashfree.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WHcustomerDetails
 */
public class WHcustomerDetailsTest {
    private final WHcustomerDetails model = new WHcustomerDetails();

    /**
     * Model tests for WHcustomerDetails
     */
    @Test
    public void testWHcustomerDetails() {
        // TODO: test WHcustomerDetails
    }

    /**
     * Test the property 'customerName'
     */
    @Test
    public void customerNameTest() {
        // TODO: test customerName
    }

    /**
     * Test the property 'customerId'
     */
    @Test
    public void customerIdTest() {
        // TODO: test customerId
    }

    /**
     * Test the property 'customerEmail'
     */
    @Test
    public void customerEmailTest() {
        // TODO: test customerEmail
    }

    /**
     * Test the property 'customerPhone'
     */
    @Test
    public void customerPhoneTest() {
        // TODO: test customerPhone
    }

}
