/*
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2023-08-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cashfree.model;

import java.util.Objects;
import com.cashfree.model.PaymentMethodBankTransferInPaymentsEntityBanktransfer;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.cashfree.JSON;

/**
 * payment method bank transfer object in payment entity
 */
@Schema(description = "payment method bank transfer object in payment entity")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-19T11:26:29.184559Z[Etc/UTC]")
public class PaymentMethodBankTransferInPaymentsEntity {
  public static final String SERIALIZED_NAME_BANKTRANSFER = "banktransfer";
  @SerializedName(SERIALIZED_NAME_BANKTRANSFER)
  private PaymentMethodBankTransferInPaymentsEntityBanktransfer banktransfer;

  public PaymentMethodBankTransferInPaymentsEntity() {
  }

  public PaymentMethodBankTransferInPaymentsEntity banktransfer(PaymentMethodBankTransferInPaymentsEntityBanktransfer banktransfer) {
    
    this.banktransfer = banktransfer;
    return this;
  }

   /**
   * Get banktransfer
   * @return banktransfer
  **/
  @javax.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  public PaymentMethodBankTransferInPaymentsEntityBanktransfer getBanktransfer() {
    return banktransfer;
  }


  public void setBanktransfer(PaymentMethodBankTransferInPaymentsEntityBanktransfer banktransfer) {
    this.banktransfer = banktransfer;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentMethodBankTransferInPaymentsEntity paymentMethodBankTransferInPaymentsEntity = (PaymentMethodBankTransferInPaymentsEntity) o;
    return Objects.equals(this.banktransfer, paymentMethodBankTransferInPaymentsEntity.banktransfer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(banktransfer);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentMethodBankTransferInPaymentsEntity {\n");
    sb.append("    banktransfer: ").append(toIndentedString(banktransfer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("banktransfer");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to PaymentMethodBankTransferInPaymentsEntity
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {

        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `banktransfer`
      if (jsonObj.get("banktransfer") != null && !jsonObj.get("banktransfer").isJsonNull()) {
        PaymentMethodBankTransferInPaymentsEntityBanktransfer.validateJsonElement(jsonObj.get("banktransfer"));
      }
  }


  /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to PaymentMethodBankTransferInPaymentsEntity
  */
  public static boolean validateJsonElementForOneOf(JsonElement jsonElement) throws IOException {

        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `banktransfer`
      if (jsonObj.get("banktransfer") != null && !jsonObj.get("banktransfer").isJsonNull()) {
        PaymentMethodBankTransferInPaymentsEntityBanktransfer.validateJsonElement(jsonObj.get("banktransfer"));
        return true;
      }
      return false;
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PaymentMethodBankTransferInPaymentsEntity.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PaymentMethodBankTransferInPaymentsEntity' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PaymentMethodBankTransferInPaymentsEntity> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PaymentMethodBankTransferInPaymentsEntity.class));

       return (TypeAdapter<T>) new TypeAdapter<PaymentMethodBankTransferInPaymentsEntity>() {
           @Override
           public void write(JsonWriter out, PaymentMethodBankTransferInPaymentsEntity value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PaymentMethodBankTransferInPaymentsEntity read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PaymentMethodBankTransferInPaymentsEntity given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PaymentMethodBankTransferInPaymentsEntity
  * @throws IOException if the JSON string is invalid with respect to PaymentMethodBankTransferInPaymentsEntity
  */
  public static PaymentMethodBankTransferInPaymentsEntity fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PaymentMethodBankTransferInPaymentsEntity.class);
  }

 /**
  * Convert an instance of PaymentMethodBankTransferInPaymentsEntity to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

